In [1]:
import numpy as np

#Collect Data
x = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
y = np.array([[0],[1],[1],[0]])

print x

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [2]:
print y

[[0]
 [1]
 [1]
 [0]]


In [7]:
num_epochs = 60000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [8]:
print syn0

[[ 0.73951777  0.84619074 -0.86322247 -0.12704356]
 [ 0.14557845  0.52527162 -0.44584595  0.29136124]
 [ 0.9264364  -0.15325115  0.56628439 -0.95042784]]


In [10]:
print syn1

[[-0.87469815]
 [ 0.15013467]
 [-0.82381757]
 [-0.87505727]]


In [12]:
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [18]:
#step 3 - Train Model
for j in xrange(num_epochs):
    #feedforward through layers 0,1,2
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    #Optimize prediction
    l2_error = y - l2
    
    if(j%10000) == 0:
        print "Error: "+str(np.mean(np.abs(l2_error)))
        
    #in what direction is gradient descent going
    l2_delta = l2_error*nonlin(l2, deriv=True)
    
    #how much did l1 contribute to l2 error
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error * nonlin(l1, deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
    

Error: 0.00386357447687
Error: 0.00356135772154
Error: 0.00331924813893
Error: 0.00311973279176
Error: 0.00295168548025
Error: 0.00280765698202
