In [4]:
import pandas as pd
import numpy as np #use number matrices
import matplotlib.pyplot as plt
import tensorflow as tf

In [49]:
#step ! - Load Data
dataframe = pd.read_csv('data.csv')
#remove features we dont care about
dataframe = dataframe.drop(['index', 'price', 'sq_price'],axis=1)

#First 10 rows
dataframe = dataframe[0:10]
dataframe

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [50]:
#step 2 - add labels
#1 is good, 0 is bad
dataframe.loc[:, ('y1')] = [1,1,1,0,0,1,0,1,1,1]
#y2 is the opposite of y1
dataframe.loc[:, ('y2')] = dataframe['y1'] == 0
#print TRUE/FALSE values to 1s and 0s
dataframe.loc[:, ('y2')] = dataframe['y2'].astype(int)
dataframe

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

In [51]:
#Step 3 - prepare data for tensorflow
#tensors are generic versions of vectors and matrices
#vector - list of numbers (1D tensor)
#matrix - list of list of numbers (2D Tensor)

#convert features into input tensors
inputX = dataframe.loc[:, ['area', 'bathrooms']].as_matrix()
#convert labels to input tensorx
inputY = dataframe.loc[:, ['y1', 'y2']].as_matrix()
inputX


array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [52]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [53]:
#step 4 - write out our hyperparameters
#rate of convergence
learning_rate = 0.000001
#epoch - complete training cycle
training_epochs = 2000
display_step = 50
n_samples = inputY.size

In [54]:
#step 5 - create computation graph/neural network
#for feature input examples, none means any number of examples. 2 is number of features
#placeholders are gateways for data into computational graphs
x = tf.placeholder(tf.float32,[None, 2])

#create weights
#2x2 float matrix we'll keep updating through the training process
#variables in tf hold and update paameters in memory buffers containing tensors
W = tf.Variable(tf.zeros([2,2]))

#add biases eg b in y = mx + b
b = tf.Variable(tf.zeros([2]))

#multiply our weights by our inputs
#weights are how we govern data flows in our computational graph
#multiply input by weights and add biases
y_values = tf.add(tf.matmul(x, W), b)

#apply softmax to valus we created
#softmax is our activation function. normalizes our values
y = tf.nn.softmax(y_values)

#feed in a matrix of labels
y_ = tf.placeholder(tf.float32, [None, 2])

In [55]:
#Step 6 - perform training
#create our cost function (mean squared error)
#reduce sum computes the sum of elements across dimensions of a tensor
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2 * n_samples)

#Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [56]:
#initialize variables and tensorflow session
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [57]:
#training loop
for i in range(training_epochs):
    sess.run(optimizer, feed_dict={x:inputX, y_:inputY})
    
    #write logs
    if(i) % display_step == 0:
        cc = sess.run(cost, feed_dict={x:inputX, y_:inputY})
        print "training step:", '%04d'%(i), "cost=", "{:9f}".format(cc)
        
print "Optimization Finished!"
training_cost = sess.run(cost, feed_dict={x:inputX, y_:inputY})
print "training cost=", training_cost, "w=", sess.run(W), "b=", sess.run(b), "\n"

training step: 0000 cost=  0.114959
training step: 0050 cost=  0.109540
training step: 0100 cost=  0.109540
training step: 0150 cost=  0.109540
training step: 0200 cost=  0.109540
training step: 0250 cost=  0.109540
training step: 0300 cost=  0.109540
training step: 0350 cost=  0.109540
training step: 0400 cost=  0.109539
training step: 0450 cost=  0.109539
training step: 0500 cost=  0.109539
training step: 0550 cost=  0.109539
training step: 0600 cost=  0.109539
training step: 0650 cost=  0.109539
training step: 0700 cost=  0.109539
training step: 0750 cost=  0.109539
training step: 0800 cost=  0.109539
training step: 0850 cost=  0.109539
training step: 0900 cost=  0.109539
training step: 0950 cost=  0.109539
training step: 1000 cost=  0.109539
training step: 1050 cost=  0.109539
training step: 1100 cost=  0.109539
training step: 1150 cost=  0.109538
training step: 1200 cost=  0.109538
training step: 1250 cost=  0.109538
training step: 1300 cost=  0.109538
training step: 1350 cost=  0

In [58]:
sess.run(y, feed_dict = {x:inputX})

array([[ 0.71125221,  0.28874779],
       [ 0.66498977,  0.33501023],
       [ 0.73657656,  0.26342347],
       [ 0.64718789,  0.35281211],
       [ 0.78335613,  0.2166439 ],
       [ 0.70069474,  0.29930523],
       [ 0.65866327,  0.34133676],
       [ 0.64828628,  0.35171372],
       [ 0.64368278,  0.35631716],
       [ 0.65480113,  0.3451989 ]], dtype=float32)

In [59]:
#basically all houses are good buys, 7/10
#How to improve? add a hidden layer